language: python

python:
    - "3.6"

cache: pip

branches:
  only:
    - master
    - develop

install:
  - "pip install -r .travis/requirements.txt"

before_script:
  - ./.travis/git_branch_name_linter.sh

script:
  - ./.travis/style_guide_enforcement.sh
  - ./.travis/cyclomatic_complexity_checker.sh
  - ./.travis/maintainability_checker.sh
  - tox